### ISSUE TITLE
Trying to copy a large selection (426x178) disables the mod tools

### ISSUE THREAD

**Issue by Barerock** [Silverfeelin/Starbound-WEdit#44] opened 2019-07-10 01:56 UTC
I'm trying to copy my base over to another area/planet but every time I try to copy the selection the selection window disappears and the tools stop working. This happens no matter if I'm using the compact or individual tool types. The area I'm selecting is 426 blocks wide and 178 blocks deep.
Game version: 1.4
Mod version: Latest Steam issue

**Comment by Barerock** [comment] 2019-07-10 02:01
Using the SchematicMaker also produces the same result.

**Comment by Barerock** [comment] 2019-07-10 02:08
I've solved it by increasing the ScriptInstructionLimit as stated in a lower issue.

**Comment by Silverfeelin** [comment] 2019-07-10 06:43
Duplicate of #5.

If you're having troubles getting your player character to work you could use the player unpacker and packer tool to remove the wedit schematic / stamp data from the file. If you need any help with that I can write up some steps after I get home from work.

You shouldn't increase the ScriptInstructionLimit because of issues like this. The workaround would be to copy over your structure in smaller chunks. With an update to the game I'm still hoping will come out soon it'll be possible to make some significant improvements to the way WEdit operates, but sadly Chucklefish hasn't had the time to implement it.
I can rewrite the serialization for the stamp and schematics to lower the data size of copies, but I'd probably end up doing that on the `wip-bounty` branch which won't be ready until (if even) that update ever comes out.

**Comment by Barerock** [comment] 2019-07-10 16:53
Good to know. I'll try out the un/packer. I'm used to Fallout and Skyrim modding, so I can probably figure it out right dandy. Thanks for the help!

**Comment by Barerock** [comment] 2019-07-10 18:15
I presume I am to delete the specific section that begins in "techController" and ends in "Objects" : True?

**Comment by Silverfeelin** [comment] 2019-07-10 18:42
I will have a look at the keys in <1 hour. If you're not sure what to delete it's probably safer to hold on so that you don't brick your player file.

**Comment by Barerock** [comment] 2019-07-10 18:58
Right now I'm trying to repack the file. I've got two backups, so I'm pretty okay with breaking this one.
My issue with repacking is that the program made by ThakyZ from [https://steamcommunity.com/sharedfiles/filedetails/?id=942157446] (Here) doesn't seem to want to repack the .json I've got. Powershell is being finnicky as well, and I don't want to re-edit that huge string for the schematic.
Using the common file by lyoko1 doesn't work, as my system doesn't want to make the new files for Notepad++.

**Comment by Silverfeelin** [comment] 2019-07-10 19:01
I have these simple batch scripts that pack and unpack the files for me. Just edit them in notepad and change the file paths, then drag and drop the files on top of the batch files.

[bat_versioned_json.zip](https://github.com/Silverfeelin/Starbound-WEdit/files/3379016/bat_versioned_json.zip)

For the copy, you'll want to remove `techController > techModules > scriptData > weditCopy` (listed under the module: dash).
For the schematics, remove `weditSchematics` in the same scriptData table.

**Comment by Barerock** [comment] 2019-07-10 19:19
Those 4 lines or everything underneath weditCopy? I assume it's the latter option. 
Is it important to delete the data strings associated with the wedit lines, or will they be removed automagically by the game with no reference to them?

**Comment by Silverfeelin** [comment] 2019-07-10 19:21
If you use Notepad++ with JSON as the editor language then you can fold the entire table and see what you have to remove. You can leave all the other data as is; you only have to remove the `weditCopy` and `weditSchematics` table.

**Comment by Barerock** [comment] 2019-07-10 19:27
I can do that? Guess I'll do that.

**Comment by Barerock** [comment] 2019-07-10 19:36
I've gotten this problem.
error: Error unexpected character parsing word at 469:24

**Comment by Silverfeelin** [comment] 2019-07-10 19:38
Well, the file is just plain JSON so make sure the structure is valid. You probably didn't remove the tables correctly, have a trailing comma or are lacking a comma somewhere.

https://jsonlint.com/

**Comment by Barerock** [comment] 2019-07-10 19:39
Man, I didn't even think of that. Though line 469 is quite far away from where I made edits.

**Comment by Silverfeelin** [comment] 2019-07-10 19:41
Ehh, if it's an exponential number you'll have to normalize it. Quirk of the (un)packer they provided us with.

**Comment by Barerock** [comment] 2019-07-10 19:43
Define "normalize." Square root? 
Would a "{" at the end of "scriptData" be the culprit? Here's the exact line:
"scriptData" : {

**Comment by Barerock** [comment] 2019-07-10 19:44
Sorry if you feel like you're teaching me how to write in JSON, you kinda are honestly. Great help you've been, though.

**Comment by Silverfeelin** [comment] 2019-07-10 20:09
No, some numbers are unpacked as `2e10`  or something like that, which then can't be parsed by the packer. Maybe it's easier if you attach your player file or mail it to Silverfeelin@gmail.com.

**Comment by Barerock** [comment] 2019-07-10 20:15
I've fixed up the endings of the deleted sections and found this at line 469. I don't know the exact rules, but doesn't each bracket need a partner?
Here's a copy of the table:
"ephemeralEffects" : [{
          "duration" : inf,
          "effect" : "nightarglow3"
        }, {
          "duration" : inf,
          "effect" : "darkhunternightar"
        }, {
          "duration" : inf,
          "effect" : "drainnightar"
        }]
    },
The ending curly bracket has no partner; am I right to put a pairing in front of the first bracket?

I'll email it to you as well, since you obviously know like 400% more than I do.

**Comment by Silverfeelin** [comment] 2019-07-10 20:52
The issue was the following code:
```json
      "ephemeralEffects" : [{
          "duration" : inf,
          "effect" : "nightarglow3"
        }, {
          "duration" : inf,
          "effect" : "darkhunternightar"
        }, {
          "duration" : inf,
          "effect" : "drainnightar"
        }]
```

`inf` isn't a valid JSON data type. The unpacker yielded incorrect data. I've fixed the issue in my reply to your email by changing these to 2,147,483,647, which is technically not 'infinite' but it should last you long enough. I assume simply joining the game once will reset them back to infinite, but if your buffs disappear at random dying will probably fix it.

**Comment by Barerock** [comment] 2019-07-10 20:54
I die plenty enough, so that's a relief! Thanks a ton for the work and taking time to help me out!

**Comment by Barerock** [comment] 2019-07-10 20:58
All fixed!

**Comment by Silverfeelin** [comment] 2019-07-10 21:22
Probably the edit. Any schematics you have will make your player file larger which could affect performance.

I will try to change the data structure of copies as there's significant improvements possible to slim down the size. But like I said in my first reply, the update probably won't go live if Chucklefish doesn't find the time to implement a change I've been waiting for for basically years now. I have changed _a lot_ of the code but the restructure won't work with the current game limitations.

**Comment by Barerock** [comment] 2019-07-10 22:28
Luckily, the modding community is growing, so more and more people are in demand of a change to the current system running the game. Hopefully it'll happen within the next year, what with the soda thing going on now and tons of new people coming to the scene.

**Comment by Silverfeelin** [comment] 2019-07-10 22:54
Most of the team has moved onto other games or are working on the console port. The few that still work on the game are busy making sure the game and updates work properly. There isn't much time left to add conveniences for modders that don't affect the base game. But we'll have to wait and see what happens. I'm still hopeful.

I'm going to go ahead and close this issue as the main issue is already listed in #5 and your player file is no longer broken.

**Closed by Silverfeelin** 2019-07-10 22:54 UTC

**Comment by Silverfeelin** [comment] 2019-07-11 15:59
Seems like the last developer working on Starbound has resigned. Sigh.
